{
 "title": "GlueObservability",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "query": {}
   },
   {
    "name": "JobRunId",
    "query": {}
   },
   {
    "name": "Source",
    "query": {}
   },
   {
    "name": "Sink",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "[Reliability] Job Run Errors Breakdown",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.RESOURCE_NOT_FOUND_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.UNCLASSIFIED_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.TIMEOUT_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.QUERY_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.IMPORT_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.DISK_NO_SPACE_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.COMPILATION_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.CONNECTION_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.INVALID_ARGUMENT_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.PERMISSION_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.SYNTAX_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.THROTTLING_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.DATA_LAKE_FRAMEWORK_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.UNSUPPORTED_OPERATION_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.RESOURCES_ALREADY_EXISTS_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.GLUE_INTERNAL_SERVICE_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.GLUE_OPERATION_TIMEOUT_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.GLUE_VALIDATION_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.GLUE_JOB_BOOKMARK_VERSION_MISMATCH_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.LAUNCH_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.DYNAMODB_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.GLUE_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.LAKEFORMATION_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.REDSHIFT_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.S3_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.SYSTEM_EXIT_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.error.UNCLASSIFIED_SPARK_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.driver.error.OUT_OF_MEMORY_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "count" },
     "metricName": "glue.executor.error.OUT_OF_MEMORY_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "[Throughput] Bytes Read & Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "ObservabilityGroup": "throughput",
      "JobName": "$JobName",
      "JobRunId": "$JobRunId",
      "Source": "$Source",
      "Type": "gauge"
     },
     "metricName": "glue.driver.bytesRead",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "ObservabilityGroup": "throughput",
      "JobName": "$JobName",
      "JobRunId": "$JobRunId",
      "Sink": "$Sink",
      "Type": "gauge"
     },
     "metricName": "glue.driver.bytesWritten",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "[Throughput] Records Read & Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dimensions": {
      "ObservabilityGroup": "throughput",
      "JobName": "$JobName",
      "JobRunId": "$JobRunId",
      "Source": "$Source",
      "Type": "gauge"
     },
     "metricName": "glue.driver.recordsRead",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "ObservabilityGroup": "throughput",
      "JobName": "$JobName",
      "JobRunId": "$JobRunId",
      "Sink": "$Sink",
      "Type": "gauge"
     },
     "metricName": "glue.driver.recordsWritten",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "[Resource Utilization] Worker Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "resource_utilization", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.driver.workerUtilization",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "[Resource Utilization] Disk Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "resource_utilization", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.driver.disk.used.percentage",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ObservabilityGroup": "resource_utilization", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.ALL.disk.used.percentage",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "[Job Performance] Skewness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "job_performance", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.driver.skewness.job",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "[Resource Utilization] Disk Available (GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "resource_utilization", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.driver.disk.available_GB",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ObservabilityGroup": "resource_utilization", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.ALL.disk.available_GB",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "[Executor OOM] OOM Error Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "ALL", "Type": "count" },
     "metricName": "glue.executor.error.OUT_OF_MEMORY_EXCEPTION",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "[Executor OOM] Heap Memory Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 36 },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "resource_utilization", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.ALL.memory.heap.used.percentage",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "[Driver OOM] OOM Error Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "error", "JobName": "ALL", "Type": "count" },
     "metricName": "glue.driver.error.OUT_OF_MEMORY_ERROR",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "[Driver OOM] Heap Memory Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 45 },
   "targets": [
    {
     "dimensions": { "ObservabilityGroup": "resource_utilization", "JobName": "$JobName", "JobRunId": "$JobRunId", "Type": "gauge" },
     "metricName": "glue.driver.memory.heap.used.percentage",
     "namespace": "Glue",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}